version: '3.8'

services:
  web:
    build: ./app
    command: >
      sh -c "service postgresql start &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

